Login
HerveJules/agro-com pull request #2
Opened 2019-04-16 23:41 UTC by HerveJules

## Task completed to this PR
- signup with encrypted password using bcrypt
- login and compare password to hashed password
- generating jwt which holds content for future use when needed

## Task pending on this PR
- passport authentication using jwt

## Incomplete task
- validations concerning login

2019-04-16 23:49 UTC, shemaeric requested changes
You can apply the feedbacks and test again the functionality of the PR so that we can merge.

2019-04-16 23:49 UTC, shemaeric commented on .gitignore
> +>>>>>>> 77e669c5f9638b50939b8cd25a55cdda5cddcc22
solve these errors in git ignore

2019-04-16 23:49 UTC, shemaeric commented on src/controllers/user.js
> +            console.log(userSave.password);
remove this console log.

2019-04-16 23:49 UTC, shemaeric commented on src/controllers/user.js
> +          message:'logged in successfully',
The message should be descriptive like : You have successfully logged in.

2019-04-16 23:49 UTC, shemaeric commented on src/controllers/user.js
> +          message:'incorrect password'
same, change the description of the message.

2019-04-16 23:49 UTC, shemaeric commented on src/controllers/user.js
> +        message:'incorrect email '
change the message description.

2019-04-16 23:49 UTC, shemaeric commented on src/controllers/user.js
> +          status:401,
the status returned in body is not the same as returned in the response.

2019-04-16 23:49 UTC, shemaeric commented on src/helpers/index.js
> +export default {generateHash,compareHashedPassword};
put the new line.

2019-04-16 23:49 UTC, shemaeric commented on src/routes/user.js
>  export default router;
new line here too.

2019-04-16 23:49 UTC, shemaeric commented on .babelrc
>  }
new line again.

2019-04-17 00:24 UTC, HerveJules commented on src/helpers/index.js
> +export default {generateHash,compareHashedPassword};
what do you mean?
like this
```suggestion
export default {
 generateHash,
 compareHashedPassword
};
```

2019-04-17 00:36 UTC, shemaeric approved these changes

2019-04-17 00:36 UTC, merged